### ISSUE TITLE
Rename all Test Methods and use underscore to improve readabity

### ISSUE THREAD

**Issue by kyberorg** [kyberorg/axe#713]
So `darkModeLabelExistAndVisible` should become `darkModeLabel_existAndVisible` (see baedung)
Also remove shitty "Tests that" from Javadoks.

**Comment by RishiKumarRay** [comment]
Can you tell me which files needs to be refactored?

**Comment by kyberorg** [comment]
I would suggest starting with ui tests (/src/tests/io/kyberorg/yalsee/test/ui)

**Comment by kyberorg** [comment]
Currently won't do
